## Using SVGD BNN requires passing these fields as kwargs
sigma_noise: 0.0001
sigma_w: 1
activation: "rbf"
layers: [1, 100, 100, 100, 1]
n_particles: 10
n_batches: 0
init_lr: .001
max_epochs: 10000
convergence_criteria: 0.0001
